SM-320 Multi Ticket Cost
futureversecom/sylo-ethereum-contracts pull request #167
Opened 2024-04-23 23:24 UTC by JCSanPedro

This PR adds another field to the ticketing parameters `multiReceiverFaceValue`.

This field is then used to determine pays for multi receiver redeems.

The PR also adds the script to deploy the upgraded contracts.

2024-04-26 02:24 UTC, Nick95550 requested changes
Minor comments

2024-04-26 02:24 UTC, Nick95550 commented on contracts/payments/ticketing/TicketingParameters.sol
Does it make sense to add this parameter to the initliasation function ?

2024-04-28 21:48 UTC, JCSanPedro commented on contracts/payments/ticketing/TicketingParameters.sol
> +    uint256 public multiReceiverFaceValue;
No because we haven't adjusted the name for single/one to one tickets elsewhere

2024-04-28 21:49 UTC, JCSanPedro commented on contracts/payments/ticketing/TicketingParameters.sol
No because we are upgrading the contract, not deploying a new one and initializing it with this new field

2024-04-28 23:56 UTC, Nick95550 approved these changes
LGTM

2024-04-29 03:37 UTC, teinnt reviewed
Awesome!

2024-04-29 03:37 UTC, teinnt commented on contracts/payments/ticketing/TicketingParameters.sol
> +    event MultiReceiverFaceValueUpdated(uint256 faceValue);
Maybe update this name to be more clear?

```suggestion
    event MultiReceiverFaceValueUpdated(uint256 multiReceiverFaceValue);
```

2024-04-29 03:37 UTC, teinnt commented on contracts/payments/ticketing/TicketingParameters.sol
> +    uint256 public multiReceiverFaceValue;
Should we add a comment here or in the `initialize` function that: "`multiReceiverFaceValue` was added after deploying the contract, so the `initialize` function does not have this parameter"?

2024-04-29 03:37 UTC, teinnt commented on test/payments/multiReceiverTicketing.test.ts
> +    await ticketingParameters.setMultiReceiverFaceValue(currentFaceValue);
Should we have different values for `faceValue` and `multiReceiverFaceValue` for testing?

2024-04-29 20:48 UTC, JCSanPedro commented on contracts/epochs/EpochsManager.sol
> +            uint32 decayRate,
No because we are upgrading the contracts, so we shouldn't move around the layout of the fields

2024-04-29 21:28 UTC, JCSanPedro commented on test/payments/multiReceiverTicketing.test.ts
> +    await ticketingParameters.setMultiReceiverFaceValue(currentFaceValue);
The tests in this file only use multi-receiver redemptions. So we have these tests for `multiReceiverFaceValue` and the tests in `ticketing.test.ts` for `faceValue` testing.

2024-04-29 22:01 UTC, merged