SM-329 Attached Authorized Account
futureversecom/sylo-ethereum-contracts pull request #168
Opened 2024-05-01 22:50 UTC by JCSanPedro

This PR adds an additional option for authorized accounts where the node can supply the authorized account for a receiver when redeeming tickets.

A new struct is introduced `AttachedAuthorizedAccount`. This struct contains the following:
- `account` The address of the authorized account
- `expiry` A unix timestamp in seconds to indicate when this account is no longer valid
- `proof` A message signed by the user's main account to act as proof of authorization
- `prefix`, `suffix`, and `infix` are strings used to construct the proof message. We use these values to allow experiences to create their own human-friendly proof messages.

The `IAuthorizedAccounts` also added a method for creating a proof message, and validating an attached authorized account.

To utilize the above solution, two new methods were also added to the ticketing contract: `redeemV2` and `redeemMultiReceiverV2`. These methods act very similar to the existing redeem methods, though allow specifying an authorized account for the signatures in the parameters. V2 version were made as changing the parameters is a breaking change.

The V2 will additionally validate the attached authorized accounts if they are present.

2024-05-03 02:41 UTC, teinnt reviewed
Wow, a lot of changes! All redeem and redeemV2 functions looking all great!!! Amazing PR John!!!!

2024-05-03 02:41 UTC, teinnt commented on contracts/payments/SyloTicketing.sol
> +        SignatureType receiverSigType;
Should we declare `UserSignature memory senderSig` and `receiverSig` here, so we dont need to use extra memory for `senderSigType` and `receiverSigType`?

Also, I've just tested and the default value of `sigType` is `Main`, so we just need to assign value if the type is `Authorized`.

```
        UserSignature memory senderSig;
        UserSignature memory receiverSig;

        if (ticket.sender.delegated != address(0)) {
            senderSig.sigType = SignatureType.Authorized;
        }
        if (ticket.receiver.delegated != address(0)) {
            receiverSig.sigType = SignatureType.Authorized;
        }

        senderSig.signature = _senderSig;
        receiverSig.signature = _receiverSig;

        (EpochsManager.Epoch memory epoch, bytes32 ticketHash) = validateRedeem(
            ticket,
            redeemerRand,
            senderSig,
            receiverSig
        );
```

2024-05-03 02:41 UTC, teinnt commented on contracts/payments/SyloTicketing.sol
> +            revert SenderCannotUseAttachedAuthorizedAccount();
Maybe we add a comment in the `redeemV2` and `redeemMultiReceiverV2` that sender cannot use the attached authorized account?

2024-05-03 02:41 UTC, teinnt commented on contracts/payments/SyloTicketing.sol
> -        if (!hasSigningPermission(ticket.sender, ticket.generationBlock)) {
Hmm, to be honest I think we can make if-else to reduce extra check and extra fee. But the code is pretty ugly though. Also `requireValidWinningMultiReceiverTicket`.

```
        // validate sender signature
        if (
            senderSig.sigType == SignatureType.Authorized &&
            !hasSigningPermission(ticket.sender, ticket.generationBlock)
        ) {
            revert InvalidSenderSigningPermission();
        } else if (senderSig.sigType == SignatureType.AttachedAuthorized) {
            revert SenderCannotUseAttachedAuthorizedAccount();
        } else if (!isValidTicketSig(ticket.sender, senderSig.signature, ticketHash)) {
            revert InvalidSenderSignature();
        }

        // validate receiver signature
        if (
            receiverSig.sigType == SignatureType.Authorized &&
            !hasSigningPermission(ticket.receiver, ticket.generationBlock)
        ) {
            revert InvalidReceiverSigningPermission();
        } else if (receiverSig.sigType == SignatureType.AttachedAuthorized) {
            _authorizedAccounts.validateAttachedAuthorizedAccount(
                ticket.receiver.main,
                receiverSig.attachedAuthorizedAccount
            );
        } else if (!isValidTicketSig(ticket.receiver, receiverSig.signature, ticketHash)) {
            revert InvalidReceiverSignature();
        }
```

2024-05-03 02:41 UTC, teinnt commented on test/authorizedAccount.test.ts
> +  it('reverts with error is authorized account is not signed by main account', async () => {
Can we add the case that the delegated account is changed?

2024-05-03 02:41 UTC, teinnt commented on test/payments/multiReceiverTicketing.test.ts
> +        attachedAuthorizedAccount: createEmptyAttachedAuthorizedAccount(),
It is quite annoying, but totally agree that we pass the same struct for sender and receiver.

2024-05-03 02:41 UTC, teinnt commented on test/payments/utils.ts
> +  const expiry = (block?.timestamp ?? 0) + 10000000;
Should we make `10000000` a constant if we use timestamp?

2024-05-03 06:03 UTC, JCSanPedro commented on contracts/AuthorizedAccounts.sol
> +        if (block.timestamp > account.expiry) {
I think we will try to transition towards timestamps instead of block numbers (e.g using timestamp for epoch duration) for the next seeker staking phase, so wanted to start here.

I think timestamps are okay for us because the types of attacks where ethereum nodes can manipulate timestamps doesn't really apply to us.

2024-05-06 03:12 UTC, JCSanPedro commented on test/payments/utils.ts
> +  const expiry = (block?.timestamp ?? 0) + 10000000;
I don't think it is necessary to define constants just for unit tests. In this case the value isn't really meaningful, it just has to represent some time in the future.

2024-05-06 04:06 UTC, JCSanPedro commented on contracts/AuthorizedAccounts.sol
> +     * @param infixOne String that is placed between the address and expiry in
Having `prefix`, suffix`, and `infixOne` will other experience developers more flexibility when constructing the personal message to sign. It would be even possible to define default values for this if other devs/designers don't want to think of the copy, but I don't think that is even necessary.

2024-05-06 22:34 UTC, teinnt approved these changes
LGTM!!!

2024-05-09 01:14 UTC, Nick95550 requested changes
Sweet as, just a couple minor comments

2024-05-09 01:14 UTC, Nick95550 commented on test/payments/multiReceiverTicketing.test.ts
>          senderSig,
```suggestion
        bobs[0].address,
        senderSig,
        new Uint8Array(0),
```
up to you

2024-05-09 01:14 UTC, Nick95550 commented on test/payments/multiReceiverTicketing.test.ts
> +    );
```suggestion
    const receiverSig = await createUserSignature(
      ethers.getBytes(ticketHash),
      SignatureType.AttachedAuthorized,
      bob,
      delegatedWallet,
      authorizedAccounts,
    );

    console.log('receiver sig ', receiverSig);

    await syloTicketing.redeemMultiReceiver(
      ticket,
      redeemerRand,
      bob.address,
      senderSig,
      receiverSig,
    );
```
I think this is supposed to be attactched ?

2024-05-13 03:35 UTC, JCSanPedro commented on test/payments/multiReceiverTicketing.test.ts
>          senderSig,
The isn't just a Uint8Array but is actually a struct, which is why I'm reusing it here.

2024-05-14 01:03 UTC, Nick95550 requested changes
Just two minors

2024-05-14 01:03 UTC, Nick95550 commented on test/payments/ticketing.test.ts
> +
I think this is still unused

2024-05-14 22:41 UTC, Nick95550 approved these changes
LGTM

2024-05-14 22:42 UTC, merged