SM-352 Implement Sylo Staking Manager
futureversecom/sylo-ethereum-contracts pull request #170
Opened 2024-05-30 00:39 UTC by JCSanPedro

Implements the interface and contract for Sylo Staking.

2024-05-31 04:23 UTC, Nick95550 requested changes
A couple comments

2024-05-31 04:23 UTC, Nick95550 commented on test/staking/syloStakingManager.test.ts
> +   * correctly as well.
```suggestion
   * transaction. The user's balance is also validated that it has been updated
   * correctly as well.
```

2024-06-03 21:27 UTC, JCSanPedro commented on test/staking/syloStakingManager.test.ts
> +    const { node, user } = await setupInitialStake(1000n);
The name of the field is actually `unlockAt`

2024-06-05 01:42 UTC, Nick95550 approved these changes
one little thing otherwise LGTM

2024-06-05 01:42 UTC, Nick95550 commented on test/staking/syloStakingManager.test.ts
> +    const { node, user } = await setupInitialStake(1000n);
nit: 
```suggestion
  it('reverts when transferring stake to nil address', async () => {
    const { node, user } = await setupInitialStake(1000n);
```

2024-06-13 23:14 UTC, merged