Sm 350 seekers stats oracle
futureversecom/sylo-ethereum-contracts pull request #171
Opened 2024-06-05 02:45 UTC by Nick95550

2024-06-05 04:47 UTC, JCSanPedro commented on contracts/SeekerStatsOracle.sol
> +// SPDX-License-Identifier: Apache-2.0
I think we can put this file under
```
contracts/
  staking/
    seekers/
      SeekerStatsOracle.sol
```

2024-06-05 04:49 UTC, JCSanPedro commented on contracts/ISeekerStatsOracle.sol
> +        uint256 attr_chip;
Lets name the attribute fields in mixedCase
```
uint256 attrChip;
uint256 attrDurability;
...
```

2024-06-05 04:49 UTC, JCSanPedro commented on contracts/ISeekerStatsOracle.sol
> +    function registerSeeker(Seeker calldata seeker, bytes calldata signature) external;
```suggestion
    function registerSeeker(Seeker calldata seeker, bytes calldata proof) external;
```

2024-06-05 04:50 UTC, JCSanPedro commented on contracts/ISeekerStatsOracle.sol
> +        Seeker[] calldata seekersList
```suggestion
        Seeker[] calldata seekers
```

2024-06-05 04:53 UTC, JCSanPedro commented on contracts/SeekerStatsOracle.sol
> +        uint256 attr_reactor,
```suggestion
        uint256 attrReactor,
```

Let's use mixedCase since that is the expected casing for solidity

2024-06-05 04:54 UTC, JCSanPedro commented on contracts/SeekerStatsOracle.sol
> +    error OracleCannotBeZeroAddress();
```suggestion
    error OracleAddressCannotBeNil();
```

2024-06-05 04:55 UTC, JCSanPedro commented on contracts/SeekerStatsOracle.sol
> +    address public SeekerStatsOracleAccount;
```suggestion
    address public oracle;
```

2024-06-05 04:56 UTC, JCSanPedro commented on contracts/SeekerStatsOracle.sol
> +        }
Not really necessary here since we already have this requirement whenever we set the oracle account

2024-06-05 05:01 UTC, JCSanPedro commented on contracts/SeekerStatsOracle.sol
> +        }
I think this implementation is not quite right. Seems like you're calculating the coverage for each individual Seeker, then summing them all up.

What you need to is first sum up all of the attributes, then calculate the coverage for the summed attributes.

```
uint256 totalReactor = 0;
uint256 totalCores = 0;
...

for (...) {
  totalReactor += seeker.attrReactor;
  totalCores += seeker.attrCores;
  ...
}

// calculate coverage from the summed attributes
```

2024-06-05 05:22 UTC, JCSanPedro requested changes
Great work 👍 Just some minors

2024-06-13 04:29 UTC, teinnt reviewed
Nothing wrong with the logic! Very awesome work Nick!

2024-06-13 04:29 UTC, teinnt commented on contracts/staking/seekers/SeekerStatsOracle.sol
> +        coverage += (int256(totalChip) * coverageAngle * int256(totalReactor)) / 2;
Good that is is a view function, so we don't need to consider gas cost of the calculation. Cool 🚀🚀🚀

2024-06-13 04:29 UTC, teinnt commented on contracts/staking/sylo/ISyloStakingManager.sol
> +        // Timestamp this entry was updated at
```suggestion
        // Timestamp this entry was updated at: block.timestamp
```

2024-06-13 04:29 UTC, teinnt commented on contracts/staking/sylo/ISyloStakingManager.sol
> +        // Track each stake entry associated to a node
```suggestion
        // Tracks each stake entry associated to a node
```

2024-06-13 04:29 UTC, teinnt commented on contracts/staking/sylo/ISyloStakingManager.sol
> +        // which will be the sum of all addStake and unlockStake calls
Idk, I guess this one is a bit easier to remmeber.

```suggestion
        // The sum of all addStake and unlockStake calls, held by this contract for one node
```

2024-06-13 04:29 UTC, teinnt commented on contracts/staking/sylo/ISyloStakingManager.sol
> +     */
I think if we want to comment, we can put more information or explanation. Otherwise I think `Unlocking` is clear enough to not have the comment above. You can decide.

2024-06-13 04:29 UTC, teinnt commented on contracts/staking/sylo/SyloStakingManager.sol
> +    IERC20 public _sylo;
Maybe name it `syloToken` to be safe and clear?

```suggestion
    IERC20 public _syloToken;
```

2024-06-13 04:29 UTC, teinnt commented on contracts/staking/sylo/SyloStakingManager.sol
> +    /** @notice Tracks overall total stake held by this contract */
```suggestion
    /** 
     * @notice Tracks overall total stake held by this contract 
     */
```

2024-06-13 04:29 UTC, teinnt commented on contracts/staking/sylo/SyloStakingManager.sol
> +     */
Great =)))

2024-06-13 04:29 UTC, teinnt commented on contracts/staking/sylo/SyloStakingManager.sol
> +    error NodeAddressCannotBeNil();
Should be `ZeroAddress`, because the TS won't run the function if the address is undefined or null.

```suggestion
    error SyloTokenCannotBeZeroAddress();
    error NodeCannotBeZeroAddress();
```

2024-06-13 04:29 UTC, teinnt commented on contracts/staking/sylo/SyloStakingManager.sol
> +    error CannotTransferMoreThanStaked(uint256 stakeAmount, uint256 transferAmount);
Just to be clear:

```suggestion
    error CannotUnlockMoreThanStakedAmount(uint256 stakeAmount, uint256 unlockAmount);
    error CannotTransferMoreThanStakedAmount(uint256 stakeAmount, uint256 transferAmount);
```

2024-06-13 04:29 UTC, teinnt commented on contracts/staking/sylo/SyloStakingManager.sol
> +    function initialize(IERC20 sylo, uint256 _unlockDuration) external initializer {
```suggestion
    function initialize(IERC20 syloToken, uint256 _unlockDuration) external initializer {
```

2024-06-13 04:29 UTC, teinnt commented on contracts/staking/sylo/SyloStakingManager.sol
> +    }
If we only called it twice here, I think we can make the function public so it is easier to maintain and reduce gas cost.
```suggestion
    function setUnlockDuration(uint256 _unlockDuration) public {
        if (_unlockDuration == 0) {
            revert UnlockDurationCannotBeZero();
        }

        unlockDuration = _unlockDuration;
        emit UnlockDurationUpdated(_unlockDuration);
    }
```

2024-06-13 04:29 UTC, teinnt commented on contracts/staking/sylo/SyloStakingManager.sol
> +     *   - If the specified stake value is zero
```suggestion
     *   - If the stake amount is zero
```

2024-06-13 04:29 UTC, teinnt commented on contracts/staking/sylo/SyloStakingManager.sol
> +
```suggestion
```

2024-06-13 04:29 UTC, teinnt commented on contracts/staking/sylo/SyloStakingManager.sol
> +     */
Great comment!!!

2024-06-13 04:29 UTC, teinnt commented on contracts/staking/sylo/SyloStakingManager.sol
> +        }
May be we should have a comment here, saying 
"update `unlocking.unlockAt` in case the `unlockDuration` is updated"

2024-06-13 04:29 UTC, teinnt commented on contracts/staking/sylo/SyloStakingManager.sol
> +        if (unlocking.unlockAt >= block.timestamp) {
Why we want to revert when `unlockAt == block.timestamp`? I think we should make sure other places use the same rule.

2024-06-13 04:29 UTC, teinnt commented on contracts/staking/sylo/SyloStakingManager.sol
> +        address user
Should we name it `staker` instead of `user`?

2024-06-13 04:42 UTC, Nick95550 commented on contracts/staking/seekers/SeekerStatsOracle.sol
> +            super.supportsInterface(interfaceId);
This checks that the contract implements the ERC165 interface

2024-06-13 04:43 UTC, Nick95550 commented on contracts/staking/seekers/SeekerStatsOracle.sol
> +    }
I didn't think it was needed in my opinion. Do you think it is required ?

2024-06-13 04:46 UTC, Nick95550 commented on contracts/staking/seekers/SeekerStatsOracle.sol
> +            }
Sorry I don't quite understand, add a comment describing what the check is for ?

2024-06-13 22:18 UTC, JCSanPedro commented on contracts/staking/seekers/SeekerStatsOracle.sol
> +            super.supportsInterface(interfaceId);
Hmm actually I think we don't want to check if the parent contract implements the given interfaceId. I don't think there is much value in confirming if it conforms to the given `interfaceId`

2024-06-13 22:25 UTC, JCSanPedro commented on contracts/staking/sylo/SyloStakingManager.sol
> +    error NodeAddressCannotBeNil();
The reason I named it `Nil` is because that in Solidity, a zero-address does not always mean that no value was passed in or set. So I think using `Nil` makes it more clear that the method revert unless a non-null value is passed in.

Also, it is wrong to think in the context of TS when implementing Solidity. TS is just one way to write code to interact with Solidity.

In other languages, instead of passing in `ethers.ZeroAddress`, you could pass in empty `bytes`, and the solidity run time will decode that into the zero address (default value for null address).

2024-06-13 22:26 UTC, JCSanPedro commented on contracts/staking/sylo/SyloStakingManager.sol
> +    error CannotTransferMoreThanStaked(uint256 stakeAmount, uint256 transferAmount);
Hmm honestly seems unnecessarily verbose to me.

2024-06-13 22:27 UTC, JCSanPedro commented on contracts/staking/sylo/SyloStakingManager.sol
> +    }
I think `external` methods are cheaper than `public` methods https://ethereum.stackexchange.com/questions/19380/external-vs-public-best-practices

2024-06-13 22:31 UTC, JCSanPedro commented on contracts/staking/sylo/ISyloStakingManager.sol
> +     */
Fair point. I think we can keep that in mind in the future, and in general try to write code that is self documenting.

2024-06-13 22:34 UTC, JCSanPedro commented on contracts/staking/sylo/SyloStakingManager.sol
> +        if (unlocking.unlockAt >= block.timestamp) {
hmm yes, seems like it should only revert when it is greater

2024-06-13 22:35 UTC, JCSanPedro commented on contracts/staking/sylo/SyloStakingManager.sol
> +        address user
I think `node`/`user` is more clear, and easier to read than `stakee`/`staker`

2024-06-13 23:07 UTC, teinnt commented on contracts/staking/seekers/SeekerStatsOracle.sol
> +    }
Yeah, for me I think should be. Because we wanna keep it consistent whenever we update parameter.

2024-06-13 23:10 UTC, teinnt commented on contracts/staking/seekers/SeekerStatsOracle.sol
> +            }
That's okay. I mean a developer will need time to understand. Oh, why `SeekerNotRegistered` but use `==`? Then they will read the check carefully, and understand, oh, because compare with `defaultSeeker`! -> It takes time (actually I was like that). We can just add a comment above, like: `If registeredSeeker is defaultSeeker -> Seeker is not registered`

2024-06-13 23:11 UTC, teinnt commented on contracts/staking/sylo/SyloStakingManager.sol
> +    error NodeAddressCannotBeNil();
Gotcha

2024-06-13 23:13 UTC, teinnt commented on contracts/staking/sylo/SyloStakingManager.sol
> +        address user
Great, I will keep that in mind for later consistency.

2024-06-13 23:14 UTC, teinnt approved these changes
Perfect!!!

2024-06-13 23:14 UTC, merged