Sm 352 seeker staking
futureversecom/sylo-ethereum-contracts pull request #172
Opened 2024-06-07 02:18 UTC by Nick95550

2024-06-09 23:09 UTC, JCSanPedro commented on contracts/staking/seekers/SeekerStakingManager.sol
> +    function transferStakedSeeker(address fromNode, address toNode, uint256 seekerId) external {
I realise there is probably not a need for a transfer function, since there is no unlocking period for staked seekers 😓

2024-06-09 23:12 UTC, JCSanPedro commented on contracts/staking/seekers/SeekerStakingManager.sol
> +        stakedSeekersByUser[msg.sender].push(seeker.seekerId);
One thing we also need to take into account is what happens if the Seeker is already staked and then you stake it again. It looks like with the current implementation if you stake the same seeker twice, you end up with both being staked. However what should happen is that on the second stake call, it effectively unstakes the original stake.

I would recommend writing an internal `_unstake` method that unstakes the seekers (deletes the values in `stakedSeekersById`, `stakedSeekersByNode` and `stakedSeekersByUser`), and calling this `_unstake` method both when staking and unstaking

2024-06-09 23:16 UTC, JCSanPedro commented on contracts/staking/seekers/SeekerStakingManager.sol
> +    function stakeSeeker(
I think because we want users to be able to stake multiple seekers in a single transaction, we need a method like this as well
```
stakeSeekers(address node, SeekerStatsOracle.Seeker[] calldata seekers, bytes[] calldata seekerStatProofs)
```
and you can move the implementation for `stakeSeeker` into an internal method `_stakeSeeker`

```
function stakeSeeker(node, seeker, seekerStatsProof) {
  _stakeSeeker(node, seeker, seekerStatsProof);
}

function stakeSeekers(node, seekers, seekerStatsProofs) {
  for (uint256 i = 0; seekers.length; ++i) {
    _stakeSeeker(node, seekers[i], seekerStatsProofs[i]);
  }
}
```

2024-06-09 23:17 UTC, JCSanPedro commented on contracts/staking/seekers/SeekerStakingManager.sol
> +        for (uint256 i = 0; i < stakedSeekersByNode[fromNode].length; i++) {
We should use `++i` instead of `i++`.https://ethereum.stackexchange.com/questions/133161/why-does-i-cost-less-gas-than-i

2024-06-09 23:18 UTC, JCSanPedro requested changes
Nice work 👍

2024-06-17 23:16 UTC, teinnt reviewed
Wow awesome!!! Very cool PR!!! I am glad to review this PR! Thanks Nick!!!!!

2024-06-17 23:16 UTC, teinnt commented on contracts/staking/seekers/SeekerStakingManager.sol
> +        }
Hmm, I dont think we should auto unstake for them. They should do this themselves, or just transfer the seeker ownership. This code needs a comment to warn users, here or in the `@notice` comment. But I think we should just revert here instead of auto unstake for the user. It makes the code clearer and be strict for what it should do. What do you think?

2024-06-17 23:16 UTC, teinnt commented on contracts/staking/seekers/SeekerStakingManager.sol
> +     */
Similar to `_stakeSeeker`, should we remove comment here too? Or we should add more info, like: `replaces the last stakedSeeker with the unstakedSeeker index in stakedSeekersByNode and stakedSeekersByUser arrays and delete it in the stakedSeekersById`

Up to you.

BTW GREAT FUNCTION!!!

2024-06-17 23:16 UTC, teinnt commented on contracts/staking/seekers/SeekerStakingManager.sol
> +        if (err == StakedErrors.NIL) {
```suggestion
        if (_isSeekerStakedError(node, seeker.seekerId) == StakedErrors.NIL) {
```

2024-06-17 23:16 UTC, teinnt commented on contracts/staking/seekers/SeekerStakingManager.sol
> +     * @notice Get a staked seeker by node address
```suggestion
     * @notice Get all seekers that were staked to a specific node address
```

2024-06-21 00:31 UTC, Nick95550 commented on contracts/staking/seekers/SeekerStakingManager.sol
> +        }
I actually did this on Johns recommendation, I think I tend to agree with your pov though. https://github.com/futureversecom/sylo-ethereum-contracts/pull/172#discussion_r1632416832

2024-06-21 01:02 UTC, Nick95550 commented on contracts/staking/seekers/SeekerStatsOracle.sol
>      function registerSeekerRestricted(Seeker calldata seeker) external {
hmm I think that restricted here applies to the oracle account but the setOracle is restrictred to the deployer, so they are different ?

2024-06-21 01:30 UTC, JCSanPedro commented on contracts/staking/seekers/SeekerStakingManager.sol
> +        }
I don't think the user should have to `unstake` then `stake` again (2 transactions) just to move their staked seeker.

I agree that the @notice comment should mention that it will unstake the seeker if it is already staked.

2024-06-21 01:54 UTC, teinnt approved these changes
LGTM!!!! GREAT PR!!!!

2024-06-21 01:54 UTC, merged