SM-367 Staking Orchestrator
futureversecom/sylo-ethereum-contracts pull request #180
Opened 2024-07-11 21:26 UTC by JCSanPedro

Includes the implementation for the Staking Orchestrator contract.

It's recommended to first refamiliarize yourself with the documentation for the staking mechanics https://www.notion.so/futureverse/Seeker-Network-Staking-Protocol-Overview-6497ad00dc844e829162347b29f9d0f9.

Then read over the contract docs https://github.com/futureversecom/sylo-ethereum-contracts/blob/SM-367-staking-orchestrator/contracts/staking/StakingOrchestrator.sol#L15-L107 to understand how the contract achieves the above mechanics.

The tests cases are also useful for understanding the nuances in the staking mechanics.

2024-07-15 05:32 UTC, Nick95550 requested changes
Mostly wording changes otherwise I think everything seems to be in order

2024-07-16 22:40 UTC, JCSanPedro commented on contracts/staking/StakingOrchestrator.sol
> + * parameter, and summing those two values together.
Hmm I don't think the suggested change makes sense here

2024-07-16 22:44 UTC, JCSanPedro commented on contracts/staking/StakingOrchestrator.sol
> +    ) internal view returns (uint256) {
Agreed 👍 . Have changed `SeekerBonus` descriptor to `SeekerPenalty`

2024-07-16 22:47 UTC, JCSanPedro commented on contracts/staking/StakingOrchestrator.sol
> +        }
Yes, good question. It can happen if the user removes `seeker` stake, but still has enough staking capacity to cover their existing `sylo` stake.

2024-07-16 22:57 UTC, JCSanPedro commented on test/staking/stakingOrchestrator.test.ts
> +      }
At cycle 6, we change the stake, so it is a little bit difficult to predict what the expected reward cycle stake should be

2024-07-16 23:00 UTC, JCSanPedro commented on test/staking/stakingOrchestrator.test.ts
> +      await checkNodeStake(node, expectedUserStake / penaltyFactor);
Refers to the fact that if we have the following users with the following stakes
```
user1Stake = 100
```
then the nodes total stake is `100` (sum of all user stakes)

But then we also have to take into consideration the node's staking capacity, which is `0` in this case, so we divide `100` by the penalty factor

2024-07-16 23:01 UTC, JCSanPedro commented on test/staking/stakingOrchestrator.test.ts
> +      const { setTimeSinceStart } = await startProtocol();
It's easier to use `startProtocol` as it will automatically set the time to exactly when the protocol starts. But if you could calculate it, you could also use `increase` here

2024-07-17 23:23 UTC, Nick95550 commented on test/staking/stakingOrchestrator.test.ts
> +      await checkNodeStake(node, expectedUserStake / penaltyFactor);
Right so shouldn't it say something similar to 'penalised by the penalty factor'

2024-07-17 23:34 UTC, Nick95550 commented on test/staking/stakingOrchestrator.test.ts
> +      }
hmm I thought it would have been equal to the updatedUserStake

2024-07-17 23:34 UTC, Nick95550 commented on contracts/staking/seekers/SeekerStakingManager.sol
> +    function initialize(IERC721 _rootSeekers, ISeekerStatsOracle _oracle, IStakingOrchestrator _stakingOrchestrator) external initializer {
I think you missed this

2024-07-17 23:34 UTC, Nick95550 commented on contracts/staking/sylo/SyloStakingManager.sol
I think you missed this

2024-07-18 03:22 UTC, JCSanPedro commented on test/staking/stakingOrchestrator.test.ts
> +      }
No because it changes once the cycle has already started, so it is not applied at the full amount

2024-07-18 03:23 UTC, JCSanPedro commented on test/staking/stakingOrchestrator.test.ts
> +      await checkNodeStake(node, expectedUserStake / penaltyFactor);
Well yes, "penalised by the penalty factor based on the node's staking capacity"

2024-07-19 01:51 UTC, merged