SM-385 CLI
futureversecom/sylo-ethereum-contracts pull request #186
Opened 2024-08-11 22:48 UTC by JCSanPedro

This is a supporting PR for SM-385. It's main contribution is that it re-implements the deployment script, and also the initialisation script for the local test network.

We also move from `ganache -> foundry anvil` for the local test node. Ganache has been deprecated, whilst anvil is still being supported, and allows us to save chain state with the `--state state.json` option.

Testing the CLI has also prompted some minor changes/fixes in the contract code, which has been included in this PR as well. These changes include:

* Allowing protocol time manager to get next before protocol has started
* Adding method to Directory to get all entries for a given directory

2024-08-14 00:59 UTC, Nick95550 requested changes
Just a couple minors

2024-08-14 00:59 UTC, Nick95550 commented on contracts/staking/StakingOrchestrator.sol
> +        _grantRole(onlyStakingManager, address(_seekerStakingManager));
I think we should create a seperate role for this

2024-08-14 00:59 UTC, Nick95550 commented on contracts/Directory.sol
> +        return (nodes, boundaries);
Whats the reason for storing a varibale in entry here ?

2024-08-14 00:59 UTC, Nick95550 commented on docker/localhost-with-protocol/README.md
> +docker run -p 8545:8545 dn3010/sylo-ethereum-testnet:0.1.0 `bash -c ganache-cli --host 0.0.0.0 --db ganache-data --blockTime 5`
I think these need editing

2024-08-14 00:59 UTC, Nick95550 commented on contracts/Directory.sol
> +        return (nodes, boundaries);
Also what is the benefit in returning the boundaries ?

2024-08-19 21:29 UTC, JCSanPedro commented on contracts/staking/StakingOrchestrator.sol
> +        _grantRole(onlyStakingManager, address(_seekerStakingManager));
It's intended for the `onlyStakingManager` to cover both roles. Seems redundant to define two distinct roles

2024-08-19 21:33 UTC, JCSanPedro commented on contracts/Directory.sol
> +        return (nodes, boundaries);
It is just a generally useful utility method for debugging. Allows us to see all of the nodes that have joined a directory, and what staking value they joined with.

2024-08-19 21:47 UTC, JCSanPedro commented on contracts/Directory.sol
> +        return (nodes, boundaries);
It also allows a local client to perform the scan method locally which is benefecial if it knows it will need to call scan multiple times for the same directory.

2024-08-19 23:26 UTC, merged